apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicebot
  namespace: local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servicebot-role
  namespace: local
rules:
  - apiGroups: ["apps"]
    resources:
      - pods
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicebot-binding
  namespace: local
subjects:
  - kind: ServiceAccount
    name: servicebot
    namespace: local
roleRef:
  kind: Role
  name: servicebot-role
  apiGroup: rbac.authorization.k8s.io
